#Links

[Royal Academy of Dance](http://www.rad.org.uk/)

[Imperial Society of Teachers of Dancing](http://www.istd.org/)

[Qualifications and Credit Framework](http://www.qcda.gov.uk/qualifications/60.aspx)

[Goodrich School](http://www.goodrich.org.uk)

[Goodliffe Hall](http://www.gipsyhill.org.uk/pages/the-goodliffe-hall.php)

[Antenna Studios](www.antennastudios.co.uk)

[Tinlids Parties](http://www.tinlidsparties.com/)

[Teresas Cakes](www.tereasas-cakes.webs.com) Tereasa has been making cakes for years for family and friends before starting her popular business. Cakes for all occasions, from fairy cakes to layer cakes, birthday, weddings, christenings, celebrations or just a good old dessert. Cookies also available. Just contact her if you wish to discuss your unique project.